### ISSUE TITLE
Inquiry About Parameter Settings in Ranking and Re-ranking 

### ISSUE THREAD

**Issue by Jack-ZC8** [YangRui525/KG-Rank#2]
First, I want to express my appreciation for your open-source code! It's a valuable contribution that significantly advances research in medical knowledge graphs.

https://github.com/ruiyang-medinfo/KG-Rank/blob/947678546797b772324d70c7348a643cd5572093/KG-Rank-UMLS/umls_rerank_medcpt.py#L179
https://github.com/ruiyang-medinfo/KG-Rank/blob/947678546797b772324d70c7348a643cd5572093/KG-Rank-UMLS/umls_rerank_medcpt.py#L185

I have a quick question regarding the threshold values of relation_scores and cross_encoded_scores (as shown above), which are set to 200 and 20, respectively. Is there a specific rationale behind these values?

**Comment by ruiyang-medinfo** [comment]
Hi, thank you for your interest in our research. The parameter settings are based on extensive ablation studies, where we tested different combinations while considering the prompt length and cost. In the end, we chose 200 and 20 as the thresholds.

However, this doesn’t necessarily mean that these thresholds are optimal, so I recommend conducting tests based on your LLMs and consider other factors. If you have any further questions, please let me know.

Thanks!

**Comment by Jack-ZC8** [comment]
OK, thanks for your reply!
