### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by fater408** [YangRui525/KG-Rank#3]
Hello, I have learned a lot from reading your paper, but when trying to run the code, I found that you did not provide the code for the evaluation section. I tried using code on the internet to calculate metrics such as BLEURT and BertScore, and found significant differences from paper. May I ask if you can provide the code for the evaluation section

**Comment by ruiyang-medinfo** [comment]
Thank you for your interest in our paper. The differences might be due to the selection of metrics. I have provided the metrics we used. Thank you.

from evaluate import load
bertscore = load("bertscore")
bleurt = load("bleurt", "BLEURT-20-D3", module_type="metric")
