### ISSUE TITLE
How to RUN

### ISSUE THREAD

**Issue by Ttchance** [YangRui525/KG-Rank#4]
Hello!I have learned a lot from your paper, and I truly admire your work. I am currently trying to reproduce your model, but I am a bit unsure about which file serves as the starting point for running the code. Could you kindly let me know which file I should begin with?Thank you very much for your time and assistance!

**Comment by ruiyang-medinfo** [comment]
Hi, thank you for your interest in my research. The six python files in "KG-Rank-UMLS" that start with "umls" represent different experimental settings. You can refer to our paper for detailed explanations and choose any one of them to run. The "gpt_umls" and "llama_umls" files correspond to the integration of GPT and Llama with the KG-Rank framework, respectively. You can run these as needed or opt for other models based on your requirements.
